### PR TITLE
Security

### PR DESCRIPTION
**Pull request by xoity**

### CODE REVIEW

**Comment by tobiasGuta** [comment]
Hey [xoity](https://github.com/xoity).

Thank you for the pull request and your valuable support to the project!

-q I appreciate your idea of ​​adding exit options and real-time monitoring features. However, I ran into some problems when trying to install the curses module required to use the interface. Terminal type Even though I tried my best to install it. But I encountered a bug in the installation process. This makes moving forward with the deployment challenging…

However, I still find the original idea very useful and would like to integrate real-time checking and the -q exit function into the project. I plan to use these features without relying on the curses module, which avoids installation complexity to provide the functionality you're looking for...

Thank you again for your feedback. I will continue to integrate these features and keep you posted on

**Comment by tobiasGuta** [comment]
``

**Comment by tobiasGuta** [comment]
hey [xoity](https://github.com/xoity).

Thank you for the pull request and your valuable support to the project!

-q I appreciate your idea of ​​adding exit options and real-time monitoring features. However, I ran into some problems when trying to install the curses module required to use the interface. Terminal type Even though I tried my best to install it. But I encountered a bug in the installation process. This makes moving forward with the deployment challenging…

However, I still find the original idea very useful and would like to integrate real-time checking and the -q exit function into the project. I plan to use these features without relying on the curses module, which avoids installation complexity to provide the functionality you're looking for...

Thank you again for your feedback. I will continue to integrate these features and keep you posted on

**Comment by xoity** [comment]
> hey [xoity](https://github.com/xoity).
> 
> 
> 
> Thank you for the pull request and your valuable support to the project!
> 
> 
> 
> -q I appreciate your idea of ​​adding exit options and real-time monitoring features. However, I ran into some problems when trying to install the curses module required to use the interface. Terminal type Even though I tried my best to install it. But I encountered a bug in the installation process. This makes moving forward with the deployment challenging…
> 
> 
> 
> However, I still find the original idea very useful and would like to integrate real-time checking and the -q exit function into the project. I plan to use these features without relying on the curses module, which avoids installation complexity to provide the functionality you're looking for...
> 
> 
> 
> Right now, you can test the tool again with the changes I made. I added the real-time monitor, an interval for refreshing depending on how many seconds you want to wait between updates, and the ability to quit using Ctrl+C.
> 
> 
> 
> Thank you again for your feedback. I will continue to integrate these features and keep you posted on 
> 
> 
> 
> 

hey tobias, i understand your concerns and validity of not having to use the cursors library, i will look into your changes and will continue to follow along. 

if you don't mind i hope to still be a contributor to this project, as contribution is the driving factor to open source development.

**Comment by tobiasGuta** [comment]
Thanks for understanding my concerns, and I appreciate you looking into the changes. I agree, contribution is essential to the growth of open-source projects, and I’m glad to hear that you’d like to continue contributing.

I’ve also sent you an invitation to be a collaborator on the project. I’m definitely open to collaborating, and I’m sure we can work together to make the project even better.

**Comment by xoity** [comment]
> Thanks for understanding my concerns, and I appreciate you looking into the changes. I agree, contribution is essential to the growth of open-source projects, and I’m glad to hear that you’d like to continue contributing.
> 
> I’ve also sent you an invitation to be a collaborator on the project. I’m definitely open to collaborating, and I’m sure we can work together to make the project even better.

sounds great, ill keep opening some pull requests but ill keep everything small scale, feel free to give any more concerns there or suggestions for the code in the review section.

again like i said i will keep everything small scale instead of big changes with +200 diffs lmao. excited to work with you and thanks for the collaborator invite.

**Comment by tobiasGuta** [comment]
Thanks for the update! That sounds like a good plan keeping things small scale will definitely help with easier reviews and faster iterations. I'll make sure to provide feedback in the review section as we go.

**Pull request closed without merging**
